"""backref-goods

Revision ID: 27e9a6a50f68
Revises: a348119bd023
Create Date: 2021-04-28 18:59:13.881495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e9a6a50f68'
down_revision = 'a348119bd023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
