"""fix-defaults

Revision ID: a348119bd023
Revises: e91bdbd5928e
Create Date: 2021-04-26 20:30:18.683004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a348119bd023'
down_revision = 'e91bdbd5928e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
